# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'Node.js CI'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2.3.5'

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v2.4.1'
        with:
          node-version: 'lts/*'

      - name: 'Install dependencies'
        run: 'npm install'

      - name: 'Package the extension'
        run: 'npm run package'

      - name: 'Lint'
        run: 'npm run lint'

      - name: 'Test'
        run: 'xvfb-run -a npm test'
