# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'Node.js CI'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: 'actions/checkout@v2'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: 'actions/setup-node@v2.1.4'
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install dependencies'
        run: 'npm install'

      - name: 'Package the extension'
        run: 'npm run package'

      - name: 'Lint'
        run: 'npm run lint'
